# Generated by Django 5.1.1 on 2024-10-29 01:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Transaction',
            fields=[
                ('type_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('object_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('show_object', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('last_change', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, default='object_images/image.png', upload_to='object_images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 10, 29, 1, 27, 44, 460663, tzinfo=datetime.timezone.utc))),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('object_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Objects.objects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.type_transaction')),
            ],
        ),
    ]
